[project]
name = "links-to-epub"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "convertext>=0.1.3",
    "docling>=2.63.0",
    "fastapi>=0.121.3",
    "feedgen>=1.0.0",
]
